# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ICT for Managers
email: josef.pospisil@laststar.eui
description: > # this means to ignore newlines until "baseurl:"
  Commented presentations for study block of subject ICT  for Managers as taught from
  15th to 18th December 2015.
baseurl: "/ictm" # the subpath of your site, e.g. /blog
url: "http://pepe.github.io/ictm" # the base hostname & protocol for your site
twitter_username: damnpepe
github_username:  pepe

# Build settings
markdown: kramdown
